# Generated by Django 5.1.7 on 2025-07-18 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Марка')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Опрема')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наслов')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Година на производство')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизел'), ('electric', 'Електричен'), ('ethanol', 'Етанол'), ('methane', 'Метан'), ('lpg', 'Плин/Бензин'), ('hybrid_petrol', 'Хибрид/Бензин'), ('hybrid_diesel', 'Хибрид/Дизел')], max_length=20, verbose_name='Тип на гориво')),
                ('transmission', models.CharField(choices=[('manual', 'Рачен'), ('automatic', 'Автоматски'), ('other', 'Друго')], max_length=20, verbose_name='Менувач')),
                ('body_type', models.CharField(choices=[('compact', 'Мал автомобил'), ('sedan', 'Седан'), ('hatchback', 'Хеџбек'), ('wagon', 'Караван'), ('coupe', 'Купе'), ('cabriolet', 'Кабриолет'), ('suv', 'Теренско'), ('minivan', 'Миниван')], max_length=20, verbose_name='Тип на каросерија')),
                ('registration_type', models.CharField(choices=[('mk', 'Македонска'), ('foreign', 'Странска'), ('none', 'Останува да се регистрира'), ('other', 'Друго')], max_length=20, verbose_name='Регистрација')),
                ('engine_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кубикажа (cm³)')),
                ('kilowatts', models.PositiveIntegerField(verbose_name='Киловати')),
                ('price', models.PositiveIntegerField(verbose_name='Цена (во евра)')),
                ('sold', models.BooleanField(default=False, verbose_name='Продадено')),
                ('mileage', models.CharField(choices=[('5000', '5.000 km'), ('10000', '10.000 km'), ('15000', '15.000 km'), ('20000', '20.000 km'), ('25000', '25.000 km'), ('30000', '30.000 km'), ('35000', '35.000 km'), ('40000', '40.000 km'), ('45000', '45.000 km'), ('50000', '50.000 km'), ('55000', '55.000 km'), ('60000', '60.000 km'), ('65000', '65.000 km'), ('70000', '70.000 km'), ('75000', '75.000 km'), ('80000', '80.000 km'), ('85000', '85.000 km'), ('90000', '90.000 km'), ('95000', '95.000 km'), ('100000', '100.000 km'), ('110000', '110.000 km'), ('120000', '120.000 km'), ('130000', '130.000 km'), ('140000', '140.000 km'), ('150000', '150.000 km'), ('160000', '160.000 km'), ('170000', '170.000 km'), ('180000', '180.000 km'), ('190000', '190.000 km'), ('200000', '200.000 km'), ('210000', '210.000 km'), ('220000', '220.000 km'), ('230000', '230.000 km'), ('240000', '240.000 km'), ('250000', '250.000 km'), ('260000', '260.000 km'), ('270000', '270.000 km'), ('280000', '280.000 km'), ('290000', '290.000 km'), ('300000', '300.000 km'), ('310000', '310.000 km'), ('320000', '320.000 km'), ('330000', '330.000 km'), ('340000', '340.000 km'), ('350000', '350.000 km'), ('360000', '360.000 km'), ('370000', '370.000 km'), ('380000', '380.000 km'), ('390000', '390.000 km'), ('400000', '400.000 km'), ('410000', '410.000 km'), ('420000', '420.000 km'), ('430000', '430.000 km'), ('440000', '440.000 km'), ('450000', '450.000 km'), ('other', 'Друго')], max_length=20, verbose_name='Километража')),
                ('color', models.CharField(choices=[('black', 'Црна'), ('white', 'Бела'), ('gray', 'Сива'), ('green', 'Зелена'), ('blue', 'Сина'), ('yellow', 'Жолта'), ('orange', 'Портокалова'), ('other', 'Друго')], max_length=20, verbose_name='Боја')),
                ('seats', models.CharField(choices=[('3', '3 седишта'), ('5', '5 седишта'), ('7', '7 седишта')], max_length=2, verbose_name='Број на седишта')),
                ('main_image', models.ImageField(upload_to='cars/main_images/', verbose_name='Главна слика')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Креирано')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealership_app.carbrand')),
                ('equipment', models.ManyToManyField(blank=True, to='dealership_app.carequipment', verbose_name='Опрема')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/extra_images/', verbose_name='Дополнителна слика')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dealership_app.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Модел')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='dealership_app.carbrand')),
            ],
            options={
                'ordering': ['brand__name', 'name'],
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.AddField(
            model_name='car',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealership_app.carmodel'),
        ),
    ]
