# Generated by Django 5.1.7 on 2025-07-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('black', 'Црна'), ('white', 'Бела'), ('gray', 'Сива'), ('red', 'Црвена'), ('green', 'Зелена'), ('blue', 'Сина'), ('yellow', 'Жолта'), ('orange', 'Портокалова'), ('brown', 'Кафеава'), ('gold', 'Златна'), ('purple', 'Виолетова'), ('other', 'Друго')], max_length=20, verbose_name='Боја'),
        ),
    ]
