# Generated by Django 5.1.7 on 2025-07-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_app', '0002_alter_car_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='extra_images',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнителни слики (JSON list of URLs)'),
        ),
    ]
