# Generated by Django 5.1.7 on 2025-07-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_app', '0003_car_extra_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='extra_images',
        ),
    ]
