# Generated by Django 5.1.7 on 2025-08-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_app', '0004_remove_car_extra_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carequipment',
            options={},
        ),
        migrations.AlterField(
            model_name='car',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='dealership_app.carequipment'),
        ),
        migrations.AlterField(
            model_name='carequipment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(upload_to='cars/extra_images/'),
        ),
    ]
