# Generated by Django 5.1.7 on 2025-08-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_app', '0005_alter_carequipment_options_alter_car_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('compact', 'Мал автомобил'), ('sedan', 'Седан'), ('hatchback', 'Хеџбек'), ('wagon', 'Караван'), ('coupe', 'Купе'), ('cabriolet', 'Кабриолет'), ('suv', 'Теренско'), ('minivan', 'Миниван'), ('kombe', 'Комбе'), ('pickup', 'Пикап'), ('motorcycle', 'Мотор')], max_length=20, verbose_name='Тип на каросерија'),
        ),
    ]
