# Generated by Django 5.1.7 on 2025-08-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_app', '0006_alter_car_body_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['position', '-created_at'], 'verbose_name': 'Автомобил', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AddField(
            model_name='car',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Позиција за подредување на возилата', verbose_name='Позиција'),
        ),
    ]
