# Generated by Django 5.1.7 on 2025-08-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_app', '0007_alter_car_options_car_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carimage',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='carimage',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Position'),
        ),
    ]
