# Generated by Django 5.1.7 on 2025-08-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_app', '0008_alter_carimage_options_carimage_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carequipment',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
