# Generated by Django 4.2.23 on 2025-09-01 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_app', '0011_alter_carequipment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(help_text='Внесете километража во километри (max: 2,000,000)', validators=[django.core.validators.MaxValueValidator(2000000)], verbose_name='Километража (км)'),
        ),
    ]
