# Generated by Django 4.2.23 on 2025-09-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_app', '0012_alter_car_mileage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carequipment',
            name='name',
        ),
        migrations.AddField(
            model_name='carequipment',
            name='name_en',
            field=models.CharField(default='Equipment', max_length=100, verbose_name='English'),
        ),
        migrations.AddField(
            model_name='carequipment',
            name='name_mk',
            field=models.CharField(default='Equipment', max_length=100, verbose_name='Македонски'),
        ),
    ]
