# Generated by Django 4.2.23 on 2025-09-01 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_app', '0013_remove_carequipment_name_carequipment_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(help_text='Внесете километража во километри', validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Километража (км)'),
        ),
    ]
