# Generated by Django 4.2.23 on 2025-09-01 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_app', '0014_alter_car_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveBigIntegerField(help_text='Внесете километража во километри (max 10 digits)', validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Километража (км)'),
        ),
    ]
