# Generated by Django 4.2.23 on 2025-09-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_app', '0015_alter_car_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveBigIntegerField(verbose_name='Километража (км)'),
        ),
    ]
