# Generated by Django 4.2.23 on 2025-09-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_app', '0016_alter_car_mileage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carequipment',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='carequipment',
            name='name_mk',
        ),
        migrations.AddField(
            model_name='carequipment',
            name='name',
            field=models.CharField(default='Equipment', max_length=100),
        ),
    ]
