# Generated by Django 4.2.23 on 2025-09-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_app', '0018_alter_car_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carequipment',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
