# Generated by Django 4.2.23 on 2025-09-02 14:55

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_app', '0019_alter_carequipment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimage',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='carimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='main_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='cars/main_images/original/', verbose_name='Главна слика'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='cars/extra_images/original/'),
        ),
    ]
