# Generated by Django 4.2.23 on 2025-09-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_app', '0020_carimage_processing_status_carimage_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='consumption',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Потрошувачка (л/100км)'),
        ),
    ]
