# Generated by Django 4.2.23 on 2025-09-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_app', '0021_car_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Достапно'), ('sold', 'Продадено'), ('pending', 'Pending'), ('coming_soon', 'Coming Soon')], default='available', max_length=15, verbose_name='Статус'),
        ),
    ]
