# Generated by Django 4.2.23 on 2025-09-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_app', '0022_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(blank=True, choices=[('sold', 'Продадено'), ('pending', 'Pending'), ('coming_soon', 'Coming Soon')], max_length=15, null=True, verbose_name='Статус'),
        ),
    ]
