# Generated by Django 4.2.23 on 2025-09-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_app', '0023_alter_car_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='status',
        ),
        migrations.AddField(
            model_name='car',
            name='banner_coming_soon',
            field=models.BooleanField(default=False, verbose_name='COMING SOON Banner'),
        ),
        migrations.AddField(
            model_name='car',
            name='banner_pending',
            field=models.BooleanField(default=False, verbose_name='PENDING Banner'),
        ),
        migrations.AddField(
            model_name='car',
            name='banner_sold',
            field=models.BooleanField(default=False, verbose_name='SOLD Banner'),
        ),
    ]
