# Generated by Django 4.2.23 on 2025-09-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_app', '0024_remove_car_status_car_banner_coming_soon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='banner_coming_soon',
        ),
        migrations.RemoveField(
            model_name='car',
            name='banner_pending',
        ),
        migrations.RemoveField(
            model_name='car',
            name='banner_sold',
        ),
        migrations.AddField(
            model_name='car',
            name='banner_type',
            field=models.CharField(blank=True, choices=[('', 'Без банер'), ('sold', 'SOLD'), ('pending', 'PENDING'), ('coming_soon', 'COMING SOON')], default='', max_length=20, verbose_name='Банер'),
        ),
    ]
