# Generated by Django 5.1.7 on 2025-09-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_app', '0025_remove_car_banner_coming_soon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_exclusive',
            field=models.BooleanField(default=False, help_text='Само едно возило може да биде ексклузивно во исто време', verbose_name='Ексклузивно возило'),
        ),
    ]
