# Generated by Django 5.1.7 on 2025-09-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_app', '0026_car_is_exclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='show_promo_badge',
            field=models.BooleanField(default=False, help_text='Прикажи црвена значка за промотивна цена', verbose_name='Промотивна цена значка'),
        ),
        migrations.AddField(
            model_name='car',
            name='show_registered_badge',
            field=models.BooleanField(default=False, help_text='Прикажи зелена значка за регистрирано', verbose_name='Регистрирано значка'),
        ),
        migrations.AddField(
            model_name='car',
            name='show_serviced_badge',
            field=models.BooleanField(default=False, help_text='Прикажи жолта значка за сервисирано', verbose_name='Сервисирано значка'),
        ),
    ]
